export const cuisineOptions = [
  { title: "African", value: "african" },
  { title: "Asian", value: "asian" },
  { title: "American", value: "american" },
  { title: "British", value: "british" },
  { title: "Cajun", value: "cajun" },
  { title: "Caribbean", value: "caribbean" },
  { title: "Chinese", value: "chinese" },
  { title: "Eastern European", value: "eastern_european" },
  { title: "European", value: "european" },
  { title: "French", value: "french" },
  { title: "German", value: "german" },
  { title: "Greek", value: "greek" },
  { title: "Indian", value: "indian" },
  { title: "Irish", value: "irish" },
  { title: "Italian", value: "italian" },
  { title: "Japanese", value: "japanese" },
  { title: "Jewish", value: "jewish" },
  { title: "Korean", value: "korean" },
  { title: "Latin American", value: "latin_american" },
  { title: "Mediterranean", value: "mediterranean" },
  { title: "Mexican", value: "mexican" },
  { title: "Middle Eastern", value: "middle_eastern" },
  { title: "Nordic", value: "nordic" },
  { title: "Southern", value: "southern" },
  { title: "Spanish", value: "spanish" },
  { title: "Thai", value: "thai" },
  { title: "Vietnamese", value: "vietnamese" },
];
